version: '3'
services:
  prereqs:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/prereqs/Dockerfile
    image: grpc-web:prereqs
  common:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/common/Dockerfile
    depends_on:
      - prereqs
    image: grpc-web:common
  echo-server:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/echo_server/Dockerfile
    depends_on:
      - common
    image: grpc-web:echo-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/envoy/Dockerfile
    image: grpc-web:envoy
    ports:
      - "8080:8080"
    links:
      - echo-server
  nginx:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/nginx/Dockerfile
    depends_on:
      - common
    image: grpc-web:nginx
    ports:
      - "8080:8080"
    links:
      - echo-server
  grpcwebproxy:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/grpcwebproxy/Dockerfile
    image: grpc-web:grpcwebproxy
    ports:
      - "8080:8080"
    links:
      - echo-server
  commonjs-client:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/commonjs_client/Dockerfile
    depends_on:
      - common
    image: grpc-web:commonjs-client
    ports:
      - "8081:8081"
  closure-client:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/closure_client/Dockerfile
    depends_on:
      - common
    image: grpc-web:closure-client
    ports:
      - "80:80"
  ts-client:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/ts_client/Dockerfile
    depends_on:
      - common
    image: grpc-web:ts-client
    ports:
      - "8082:8082"
  binary-client:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/binary_client/Dockerfile
    depends_on:
      - common
    image: grpc-web:binary-client
    ports:
      - "8081:8081"
